services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - PGDATA=/data/postgres
    restart: always
    ports:
      - '${DB_PORT}'
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - marjane

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8081:${SERVER_PORT}'
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - marjane

networks:
  marjane:
    name: marjane
    driver: bridge

volumes:
  postgres-db:
    driver: local